early postgres connection
slice/lifesaver pull request #9
Opened 2019-12-20 22:43 UTC by lun-4

closes #6

2019-12-21 04:49 UTC, slice requested changes
I don't think that the connection should be done in the constructor. Calling `Bot(...)` and having it automatically attempt to spin up a connection would be disruptive, in my opinion. I think it would be better to call `_postgres_connect` in `lifesaver.cli`.

2019-12-21 15:53 UTC, lun-4 commented
But isn't bot the one doing the side-effects of configuration reading? locking it to `lifesaver.cli` only doesn't sound like a good idea..

2019-12-23 23:42 UTC, slice commented
> But isn't bot the one doing the side-effects of configuration reading?

No? It receives the `BotConfig` object in `__init__`, it doesn't read from the filesystem or anything. Besides, I think connecting to Postgres in a constructor is out of place and pretty drastic.

> locking it to `lifesaver.cli` only doesn't sound like a good idea..

Can you elaborate on that?

2019-12-24 16:34 UTC, lun-4 commented
Consider some user of lifesaver that just wants to run a script to start the bot instead of `lifesaver.cli`, but that's likely an edge-case that can be ignored.

2019-12-25 08:12 UTC, slice commented
Yes, users should be using `lifesaver.cli`. I can provide a method to kickstart all of the required effects that `lifesaver.cli` can use if they really want to use a start script.

2019-12-29 05:49 UTC, slice requested changes

2019-12-29 05:49 UTC, slice commented on lifesaver/cli.py
> +async def _postgres_connect(bot):
The method should be kept on the bot as that's where the database lives. It should still be called from `lifesaver.cli` though.

2020-01-05 08:57 UTC, merged